### ISSUE TITLE
openwhisk-swift-precompiled-binaries Deployed action doesn't work

### ISSUE THREAD

**Issue by OlexandrStepanov** [serverless/examples#228]
Hello.

When I follow the steps from openwhisk-swift-precompiled-binaries README.md to deploy to OpenWhisk the "hello world" action, action is created, but it's invocation always fails with error:
`The action did not return a dictionary.`

Here are the logs I got:
```
[
  "2017-12-25T13:45:18.939192582Z stderr: /swift3Action/spm-build/.build/release/Action: symbol lookup error: /swift3Action/spm-build/.build/release/Action: undefined symbol: _TMps13IndexableBase",
  "2017-12-25T13:45:18.939333124Z stdout: "
]
```

I have tried steps from the [blog post](http://jamesthom.as/blog/2017/07/17/creating-swift-binaries-for-openwhisk/), results are the same.

Help is much appreciated.

With regards.
cc @jthomas.

**Comment by jthomas** [comment]
Thanks for reporting this. Let me try it out and see what happens.

**Comment by jthomas** [comment]
This issue is caused because the default swift runtime now uses 3.1.1 and the examples are compiling in the 3.0.0 runtime image.

Modify `scripts.compile` in `package.json` to be the following:

```
"compile": "docker run --rm -it -v $(pwd):/swift-package openwhisk/action-swift-v3.1.1 bash -e -c 'cd /swift-package && swift build -v -c release'"
```

The Docker image used to compile the binaries has been changed from `openwhisk/swift3action` to `openwhisk/action-swift-v3.1.1`.

Thanks for reporting this issue, I'm going to update all the examples and documentation to resolve this. I'll close this issue once I've done that.

**Comment by OlexandrStepanov** [comment]
Thanks a lot, @jthomas.
