### ISSUE TITLE
What about applying prettier to the whole codebase?

### ISSUE THREAD

**Issue by QuantumInformation** [serverless/examples#403]

**Comment by eahefnawy** [comment]
Interesting! Thanks for suggesting!

Imo this repo is full of examples from different folks with different coding styles. I'd hate to force a certain linting config on them. I'd use prettier if this repo represented a single project, but due to the nature of this repo, I don't think that would make much sense.

Just my two cents 🙌

**Comment by QuantumInformation** [comment]
Fair enough, thx.
