### ISSUE TITLE
Incompatibility with CircleCI

### ISSUE THREAD

**Issue by gpkc** [serverless/examples#428]
CircleCI doesn't support volumes when using docker, except if you are usign a machine executor, which isn't always a viable option:
https://support.circleci.com/hc/en-us/articles/360007324514-How-can-I-mount-volumes-to-docker-containers-
This makes it impossible to use the `dockerizePip` option.

**Comment by dschep** [comment]
This seems to be on the wrong repo.. `dockerizePip` is a feature of [serverless-python-requriements](https://github.com/UnitedIncome/serverless-python-requirements). But in CI, there's little reason to use that option since it's already a 64 bit linux box, so use `dockerizePip: non-linux` instead of `true`.
